---
# tasks file for ansible-role-root

- include_vars: "{{ ansible_os_family }}.yml"

- fail: msg="root_password must have a key {{ ansible_os_family }}"
  when: " {{ not ansible_os_family in root_password }}"

- fail: msg="root_password must have non-empty string in key {{ ansible_os_family }}"
  when: " {{ not root_password[ansible_os_family] }}"

- name: Create ssh directory
  file:
    path: "{{ root_home }}/.ssh"
    state: directory
    mode: 0700

- name: Create authorized_keys (root_ssh_authorized_keys_array)
  template:
    src: authorized_keys.j2
    dest: "{{ root_home }}/.ssh/authorized_keys"
    mode: 0600
  when: "{{ root_ssh_authorized_keys_array is defined and root_ssh_authorized_keys_array | length > 0 }}"

- name: Set root password
  user:
    name: "{{ root_user }}"
    password: "{{ root_password[ansible_os_family] }}"
